---
- name: Example Ansible Playbook for Handlers
  hosts: all
  become: yes
  remote_user: ubuntu
  roles:
    - handlers

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
